// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwskCHjlGONd3N9inU78JRSzpmuYYHKiE',
    appId: '1:819400014156:web:de424406d4e6628fd737e9',
    messagingSenderId: '819400014156',
    projectId: 'chatapp-e275b',
    authDomain: 'chatapp-e275b.firebaseapp.com',
    storageBucket: 'chatapp-e275b.appspot.com',
    measurementId: 'G-0DBT8NYN69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0rdYEkPCa4WE3MS8jxDZ1Yt1UilPbaA',
    appId: '1:819400014156:android:7baa35105696e19ed737e9',
    messagingSenderId: '819400014156',
    projectId: 'chatapp-e275b',
    storageBucket: 'chatapp-e275b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDkiM3qvwE1NblkIreK8j3CgA_4cZqyM',
    appId: '1:819400014156:ios:3cdbab804efc73b6d737e9',
    messagingSenderId: '819400014156',
    projectId: 'chatapp-e275b',
    storageBucket: 'chatapp-e275b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwskCHjlGONd3N9inU78JRSzpmuYYHKiE',
    appId: '1:819400014156:web:2bad0130d08c69b1d737e9',
    messagingSenderId: '819400014156',
    projectId: 'chatapp-e275b',
    authDomain: 'chatapp-e275b.firebaseapp.com',
    storageBucket: 'chatapp-e275b.appspot.com',
    measurementId: 'G-2ZSLEHBX98',
  );
}
